#ifndef LISTVA_NAMES_H
#define LISTVA_NAMES_H

#include <QStringList>

inline QStringList getListvaNames()
{
    return {
        "0d30cb0e.btx", "0e87167d.btx", "0ef26593.btx", "2a17c821.btx", "2b1a809d.btx",
        "4ertopolox.btx", "5c7cf497.btx", "13kardon_luchog.btx",
        "43tree1.btx", "43tree2.btx", "43tree3.btx", "43tree4.btx", "43tree5.btx",
        "43tree6.btx", "43tree7.btx", "43tree8.btx", "43tree9.btx",
        "44tree1.btx", "44tree2.btx", "44tree4.btx", "44tree5.btx",
        "69f35d6d.btx", "417f945c.btx", "827ccf23.btx", "1711d7a2.btx",
        "16640c7f.btx", "71595726.btx", "a5f0e960.btx",
        "ab_aqua_anenome.btx", "ab_aqua_bubbles.btx", "ab_aqua_coral.btx",
        "ab_aqua_kelp.btx", "ab_aqua_sand.btx", "ab_aqua_starfish.btx",
        "ab_aqua_tubeweed.btx", "ab_aqua_urchin.btx",
        "abies.btx", "abies3.btx", "abies4.btx", "apat_flowers.btx",
        "AppleTree.btx", "AucTreeCrone8712.btx", "AucWeed8163.btx",
        "b_craet1_4_ca.btx", "Bdup2_plant.btx", "beechalder.btx",
        "BG-Tree003LeavesArecol.btx", "birchl.btx", "borchevik.btx",
        "bpng_inc2v.btx", "bubuk21d.btx", "BukTree1.btx", "BukTree2.btx",
        "bys_appletree.btx", "bys_cherrytree.btx", "bys_flowers.btx",
        "bys_plumtree.btx", "bys_wires.btx",
        "byssch_flower1.btx", "byssch_flower2.btx", "byssch_flower3.btx",
        "byssch_flower4.btx", "byssch_flower5.btx",
        "cactusL.btx", "cannabisPod9173.btx", "CasinoNor3864.btx",
        "cedar_dcedar_a.btx", "CJ_FLOWER_256cj_flower_a.btx",
        "cj_flower(hi_res)cj_flower_a(h.btx", "cj_leaf_cheesecj_leaf_cheese_a.btx",
        "cj_lettuce_1cj_lettuce_1_a.btx", "CJ_PLANT.btx", "CJgrass.btx",
        "conop_listy_2_256.btx", "conop_listy_3.btx", "conop_listy_4_64.btx",
        "currant.btx", "de_barebranches_dde_barebranch.btx", "de07a2dc.btx",
        "derevoclub8201.btx", "derevoclub8203.btx", "derevoclub82021.btx",
        "derevoclub82022.btx", "derevopar7901.btx", "derevopar7902.btx",
        "derevopar7903.btx", "derevopar7904.btx", "derevopar7905.btx",
        "edovo_coundom_flower.btx", "edovo_coundom_gryadka.btx",
        "elm.btx", "espeb.btx", "f.btx", "f437c114.btx", "Fern_diff8472.btx",
        "fialkiflowers.btx", "firtopx.btx", "fl2_1.btx",
        "flowersbaikal.btx", "flowert.btx", "free grass.btx", "freegrass.btx",
        "galder.btx", "golovka_konop3.btx",
        "Grass_00.btx", "grass_gen256old.btx", "grass_green_long.btx",
        "grass_green_med.btx", "grass1.btx",
        "GrassA_02.btx", "GrassA_04.btx", "GrassA_05.btx",
        "GrassA_15_1.btx", "GrassA_15.btx", "GrassA_16.btx", "GrassA_20.btx",
        "GrassAlpha7453.btx", "GrassVazMast.btx",
        "gz_E2_branch_2gz_E2_branch_2_a.btx", "gz_E2_branch_3gz_E2_branch_3_a.btx",
        "gz_e2_fishleaf01gz_e2_fishleaf.btx", "gz_e2_fishleaf02gz_e2_fishleaf.btx",
        "gz_e2_fishleaf03gz_e2_fishleaf.btx", "gz_e2_leaf_cheesegz_e2_leaf_ch.btx",
        "Hazel1_branch1.btx", "Hazel2_branch1.btx", "Hazel05_branch1.btx",
        "hgj.btx", "holly.btx", "hot_flowers1.btx",
        "hunter_borwevik.btx", "hunter_bush.btx", "hunter_bush2.btx",
        "hunter_flowers.btx", "hunter_flowers2.btx", "hunter_longgrass.btx",
        "hunter_moregrass.btx", "hunter_paporotnik.btx",
        "huntre_tree_leaf.btx", "huntre_tree_pine.btx",
        "iz_moh.btx", "jed_de3.btx", "kb_ivy2_256.btx",
        "kbplanter_plants1.btx", "klubnika.btx",
        "km_v_bananaleafrsn_os_v_bananal.btx",
        "krapiva_list.btx", "kust_farm1.btx", "kustik1.btx", "kyst3.btx",
        "lentisk.btx", "list4.btx",
        "LOD_e1.btx", "LOD_eub_1.btx", "LOD_eub_2.btx",
        "LOD_norwpine1.btx", "LOD_norwpine3.btx", "LOD_papernew3.btx",
        "lod_poplar2veg.btx", "lodbushshrub11.btx",
        "lodeu_veg1.btx", "lodeu_veg2.btx",
        "LODH_leaftree_big.btx", "LODH_leaftree_med.btx", "LODH_pineangled.btx",
        "lopux_list.btx", "luchog.btx", "lupinprototype.btx",
        "mp_flowerbush.btx", "Newtreed256.btx", "newtreeleavesb128.btx",
        "nxg_im_ivy_01.btx",
        "palm8204.btx", "PalmArecaceae144.btx", "PalmWall2947.btx",
        "pberk2.btx", "pine.btx", "pinebranch1.btx",
        "planta252.btx", "plantc256.btx", "PlantH31741.btx",
        "potato.btx",
        "R_Berez1_b.btx", "R_Listv1.btx",
        "rus_grasstype4_flowers.btx", "rus_whiteflower_ingrass.btx",
        "sjmgrss.btx", "sm_quarry_Rusty.btx", "sm_redwood_branch.btx",
        "sp_branch_dsp_branch_a.btx",
        "starflower2.btx", "starflower2wht.btx", "starflower3.btx", "starflower3yel.btx",
        "Strip_plant.btx",
        "T_Ferns_374223.btx", "TK_Fern_Plant.btx", "TomatoFarm.btx",
        "tree_lodderevo1.btx", "tree_lodeubeech1.btx", "tree_lodkastan.btx",
        "tree_lodlinden.btx", "tree_lodpaper_der1.btx", "tree_lodwillow.btx",
        "TREE_STUB1.btx", "tree19Mi.btx", "TreeCron9716.btx",
        "trees_vetkagreen5.btx", "treewillow99.btx",
        "veg_LODpine3.btx", "veg_LODpine4.btx", "veg_LODpinee1.btx",
        "vegdoor1_int.btx", "vegLOD_pine4.btx",
        "vyaz_shirshavii.btx",
        "WH_flowers1.btx", "willow.btx", "wow.btx", "wow2.btx",
        "yellosmallflowers.btx", "yuka256.btx",
        "juni.btx", "kb_balcony_ferns_genintgeneric.btx", "kb_balcony_ferns.btx",
        "kbtree4_test.btx", "klengreen.btx", "km_plant1.btx",
        "km_v_vuboakm_v_vuboa_a.btx", "kolosya_rog.btx", "kustik2.btx",
        "KustRog8716.btx", "l.btx",
        "LeavesTropical0141_1.btx", "LeavesTropical0202_1.btx", "LeavesTropical0218_1.btx",
        "LOD_norwpine2.btx", "LOD_norwpine4.btx", "LOD_paperArz.btx", "LOD_papernew2.btx",
        "LODH_leaftree_root.btx", "LODH_leaftree_sml.btx", "LODH_leaftree_vol.btx",
        "LODH_pinesmall.btx", "LODH_pinetree1.btx", "LODH_pinetree2.btx",
        "LODH_pinetree3.btx", "LODH_Rdeadtree.btx",
        "lopux_koluchka.btx", "newtreeleaves128.btx",
        "Nymphalis_polycolor_bottom.btx", "Nymphalis_polycolor_top.btx",
        "orien2.btx", "oriental.btx", "Palm0471.btx",
        "planta256.btx", "PlantH1741.btx", "PlantH21741.btx", "PoleHIGHGrass1.btx",
        "poplar.btx", "poplar2.btx", "prop_plantXYLI.btx",
        "R_Berez1_t.btx", "R_Dub1.btx", "rgv4lod_mel_veg.btx",
        "RTurm_WaterDec1.btx", "RTurm_WaterDec2.btx",
        "rus_bigORGANGEflower.btx", "rus_grasstype2.btx", "rus_grassTYPE3.btx",
        "salad.btx", "sm_Agave_1.btx", "sm_Agave_2.btx", "sm_des_bush1.btx",
        "sm_minipalm1.btx", "sm_pinetreebit.btx", "sm_potplant1.btx",
        "starflower3prpl.btx", "svekla.btx", "tikva.btx", "tomato.btx",
        "tree_lodfikovnik.btx", "tree_lodpaper_der2.btx",
        "Tree.btx", "treeCRB221_1.btx", "TreeCron9716_2.btx", "tuyaclub8205.btx",
        "v54.btx",
        "veg_LODpine1.btx", "veg_LODpine2.btx", "veg_LODpine5.btx",
        "vegLOD_pine2.btx", "vegLOD_pine3.btx", "veglod_pine5.btx", "vegLOD_pinekust.btx",
        "vine_rich.btx", "VL1X8_002.btx", "willow_new.btx", "woak.btx"
    };
}

#endif